// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conversation} from '../models';
import {config} from '../models';

export function DeleteConversation(arg1:string):Promise<void>;

export function GetActiveConversation():Promise<conversation.Conversation>;

export function GetConfig():Promise<config.Config>;

export function GetSessionInfo():Promise<Record<string, any>>;

export function IsConfigured():Promise<boolean>;

export function ListConversations():Promise<Array<conversation.Summary>>;

export function LoadConversation(arg1:string):Promise<conversation.Conversation>;

export function NewConversation():Promise<conversation.Conversation>;

export function RenameConversation(arg1:string,arg2:string):Promise<void>;

export function ResetSession():Promise<void>;

export function RunAgentTask(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StopAgent():Promise<void>;

export function TestConnection():Promise<boolean|string>;
