// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {conversation} from '../models';
import {audit} from '../models';
import {azure} from '../models';
import {config} from '../models';

export function CheckEndpointHealth(arg1:string,arg2:string):Promise<boolean|string>;

export function DeleteConversation(arg1:string):Promise<void>;

export function FetchModels(arg1:string,arg2:string):Promise<Array<llm.ModelInfo>>;

export function GetActiveConversation():Promise<conversation.Conversation>;

export function GetAuditLog():Promise<Array<audit.Event>>;

export function GetAzureContext():Promise<azure.Context>;

export function GetConfig():Promise<config.Config>;

export function GetMonthlyCost(arg1:string):Promise<azure.CostSummary>;

export function GetSessionInfo():Promise<Record<string, any>>;

export function IsConfigured():Promise<boolean>;

export function ListConversations():Promise<Array<conversation.Summary>>;

export function ListResourceGroups():Promise<Array<azure.ResourceGroupSummary>>;

export function ListSubscriptions():Promise<Array<azure.Subscription>>;

export function ListVMPowerStates():Promise<Array<azure.VMPowerState>>;

export function LoadConversation(arg1:string):Promise<conversation.Conversation>;

export function NewConversation():Promise<conversation.Conversation>;

export function RenameConversation(arg1:string,arg2:string):Promise<void>;

export function ResetSession():Promise<void>;

export function ResolveProposal(arg1:string,arg2:boolean):Promise<void>;

export function RunAgentTask(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetSubscription(arg1:string):Promise<void>;

export function StopAgent():Promise<void>;

export function TestConnection():Promise<boolean|string>;
