// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetActiveConversation() {
  return window['go']['main']['App']['GetActiveConversation']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSessionInfo() {
  return window['go']['main']['App']['GetSessionInfo']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function LoadConversation(arg1) {
  return window['go']['main']['App']['LoadConversation'](arg1);
}

export function NewConversation() {
  return window['go']['main']['App']['NewConversation']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function ResetSession() {
  return window['go']['main']['App']['ResetSession']();
}

export function RunAgentTask(arg1, arg2) {
  return window['go']['main']['App']['RunAgentTask'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
